
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: quiz-backend
  labels:
    app: quiz-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: quiz-app
        tier: backend
    spec:
      containers:
      - name: quiz-backend
        image: [BACKEND_IMAGE_IDENTIFIER]
        imagePullPolicy: Always
        env:
          - name: PROJECTID
            value: [PROJECTID]
          - name: GCLOUD_BUCKET
            value: [GCLOUD_BUCKET]
